all: false
dir: '{{.InterfaceDir}}'
formatter: gofmt
recursive: true
structname: '{{.Mock}}{{firstUpper .InterfaceName}}'
filename: 'mock_{{snakecase .InterfaceName}}.go'

packages:
  github.com/collibra/go-bexpression/base:
    interfaces:
      Visitor:
      Comparison: