// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package base

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVisitor creates a new instance of MockVisitor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVisitor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVisitor {
	mock := &MockVisitor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVisitor is an autogenerated mock type for the Visitor type
type MockVisitor struct {
	mock.Mock
}

type MockVisitor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVisitor) EXPECT() *MockVisitor_Expecter {
	return &MockVisitor_Expecter{mock: &_m.Mock}
}

// EnterExpressionElement provides a mock function for the type MockVisitor
func (_mock *MockVisitor) EnterExpressionElement(ctx context.Context, element VisitableElement) error {
	ret := _mock.Called(ctx, element)

	if len(ret) == 0 {
		panic("no return value specified for EnterExpressionElement")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, VisitableElement) error); ok {
		r0 = returnFunc(ctx, element)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVisitor_EnterExpressionElement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnterExpressionElement'
type MockVisitor_EnterExpressionElement_Call struct {
	*mock.Call
}

// EnterExpressionElement is a helper method to define mock.On call
//   - ctx context.Context
//   - element VisitableElement
func (_e *MockVisitor_Expecter) EnterExpressionElement(ctx interface{}, element interface{}) *MockVisitor_EnterExpressionElement_Call {
	return &MockVisitor_EnterExpressionElement_Call{Call: _e.mock.On("EnterExpressionElement", ctx, element)}
}

func (_c *MockVisitor_EnterExpressionElement_Call) Run(run func(ctx context.Context, element VisitableElement)) *MockVisitor_EnterExpressionElement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 VisitableElement
		if args[1] != nil {
			arg1 = args[1].(VisitableElement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVisitor_EnterExpressionElement_Call) Return(err error) *MockVisitor_EnterExpressionElement_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVisitor_EnterExpressionElement_Call) RunAndReturn(run func(ctx context.Context, element VisitableElement) error) *MockVisitor_EnterExpressionElement_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveExpressionElement provides a mock function for the type MockVisitor
func (_mock *MockVisitor) LeaveExpressionElement(ctx context.Context, element VisitableElement) {
	_mock.Called(ctx, element)
	return
}

// MockVisitor_LeaveExpressionElement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveExpressionElement'
type MockVisitor_LeaveExpressionElement_Call struct {
	*mock.Call
}

// LeaveExpressionElement is a helper method to define mock.On call
//   - ctx context.Context
//   - element VisitableElement
func (_e *MockVisitor_Expecter) LeaveExpressionElement(ctx interface{}, element interface{}) *MockVisitor_LeaveExpressionElement_Call {
	return &MockVisitor_LeaveExpressionElement_Call{Call: _e.mock.On("LeaveExpressionElement", ctx, element)}
}

func (_c *MockVisitor_LeaveExpressionElement_Call) Run(run func(ctx context.Context, element VisitableElement)) *MockVisitor_LeaveExpressionElement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 VisitableElement
		if args[1] != nil {
			arg1 = args[1].(VisitableElement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVisitor_LeaveExpressionElement_Call) Return() *MockVisitor_LeaveExpressionElement_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockVisitor_LeaveExpressionElement_Call) RunAndReturn(run func(ctx context.Context, element VisitableElement)) *MockVisitor_LeaveExpressionElement_Call {
	_c.Run(run)
	return _c
}

// Literal provides a mock function for the type MockVisitor
func (_mock *MockVisitor) Literal(ctx context.Context, l interface{}) error {
	ret := _mock.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for Literal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = returnFunc(ctx, l)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVisitor_Literal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Literal'
type MockVisitor_Literal_Call struct {
	*mock.Call
}

// Literal is a helper method to define mock.On call
//   - ctx context.Context
//   - l interface{}
func (_e *MockVisitor_Expecter) Literal(ctx interface{}, l interface{}) *MockVisitor_Literal_Call {
	return &MockVisitor_Literal_Call{Call: _e.mock.On("Literal", ctx, l)}
}

func (_c *MockVisitor_Literal_Call) Run(run func(ctx context.Context, l interface{})) *MockVisitor_Literal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVisitor_Literal_Call) Return(err error) *MockVisitor_Literal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVisitor_Literal_Call) RunAndReturn(run func(ctx context.Context, l interface{}) error) *MockVisitor_Literal_Call {
	_c.Call.Return(run)
	return _c
}
