// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package base

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// NewMockComparison creates a new instance of MockComparison. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComparison(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComparison {
	mock := &MockComparison{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockComparison is an autogenerated mock type for the Comparison type
type MockComparison struct {
	mock.Mock
}

type MockComparison_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComparison) EXPECT() *MockComparison_Expecter {
	return &MockComparison_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockComparison
func (_mock *MockComparison) Accept(ctx context.Context, visitor Visitor) error {
	ret := _mock.Called(ctx, visitor)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Visitor) error); ok {
		r0 = returnFunc(ctx, visitor)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockComparison_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockComparison_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - ctx context.Context
//   - visitor Visitor
func (_e *MockComparison_Expecter) Accept(ctx interface{}, visitor interface{}) *MockComparison_Accept_Call {
	return &MockComparison_Accept_Call{Call: _e.mock.On("Accept", ctx, visitor)}
}

func (_c *MockComparison_Accept_Call) Run(run func(ctx context.Context, visitor Visitor)) *MockComparison_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Visitor
		if args[1] != nil {
			arg1 = args[1].(Visitor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComparison_Accept_Call) Return(err error) *MockComparison_Accept_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockComparison_Accept_Call) RunAndReturn(run func(ctx context.Context, visitor Visitor) error) *MockComparison_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// ToGql provides a mock function for the type MockComparison
func (_mock *MockComparison) ToGql() (BinaryExpressionUnion, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToGql")
	}

	var r0 BinaryExpressionUnion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (BinaryExpressionUnion, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() BinaryExpressionUnion); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(BinaryExpressionUnion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComparison_ToGql_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToGql'
type MockComparison_ToGql_Call struct {
	*mock.Call
}

// ToGql is a helper method to define mock.On call
func (_e *MockComparison_Expecter) ToGql() *MockComparison_ToGql_Call {
	return &MockComparison_ToGql_Call{Call: _e.mock.On("ToGql")}
}

func (_c *MockComparison_ToGql_Call) Run(run func()) *MockComparison_ToGql_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComparison_ToGql_Call) Return(binaryExpressionUnion BinaryExpressionUnion, err error) *MockComparison_ToGql_Call {
	_c.Call.Return(binaryExpressionUnion, err)
	return _c
}

func (_c *MockComparison_ToGql_Call) RunAndReturn(run func() (BinaryExpressionUnion, error)) *MockComparison_ToGql_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockComparison
func (_mock *MockComparison) Validate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockComparison_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockComparison_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockComparison_Expecter) Validate(ctx interface{}) *MockComparison_Validate_Call {
	return &MockComparison_Validate_Call{Call: _e.mock.On("Validate", ctx)}
}

func (_c *MockComparison_Validate_Call) Run(run func(ctx context.Context)) *MockComparison_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockComparison_Validate_Call) Return(err error) *MockComparison_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockComparison_Validate_Call) RunAndReturn(run func(ctx context.Context) error) *MockComparison_Validate_Call {
	_c.Call.Return(run)
	return _c
}
